name: Subtree sync PR

on:
  push:
    branches: [ "slice/internal" ]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: peter-evans/create-pull-request@v7
        with:
          branch: slice/internal
          base: master
          title: "Sync subtree"
          body:  "This PR was opened automatically after the subtree sync job pushed changes."