name: Subtree sync PR

on:
  push:
    branches: [ "slice/internal" ]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Create PR to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base master \
            --head slice/internal \
            --title "Internal Sync" \
            --body "This PR was opened automatically after the internal sync job pushed changes." \
            --repo ${{ github.repository }} \
            --fill \
            || echo "PR already exists or no changes to PR"